In [1]:
import numpy as np

In [4]:
a=np.array(4)
a 
#this is scalar>>>0-D tensor

array(4)

In [5]:
a.ndim


0

In [6]:
 b=np.array([1,2,3,4])
 b

array([1, 2, 3, 4])

In [7]:
b.ndim
#this is a 1-d tensor.

1

In [14]:
c=np.array([[1,2,3],[4,5,6]])

In [16]:
c
#this is a 2 d tensor.
c.ndim

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
d=np.array([[[56, 183, 1],
            [65, 164, 0]],
            [[85, 176, 1],
            [44, 164, 0]]])
d


array([[[ 56, 183,   1],
        [ 65, 164,   0]],

       [[ 85, 176,   1],
        [ 44, 164,   0]]])

In [20]:
d.ndim#this is a 3-d tensor

3

In [ ]:
#4-d tensors are used for images while 5 d tensors are used for videos.