In [1]:
import numpy as np
#used for mathematical computation.

In [7]:
np.ones((3,4))#3*4 matrex of one will be created

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.random.rand(33)

array([0.41834885, 0.77549175, 0.80485123, 0.67183894, 0.94231672,
       0.25598623, 0.44929012, 0.78303819, 0.47047251, 0.00318844,
       0.08175515, 0.06690648, 0.17076146, 0.41136711, 0.11748577,
       0.07053552, 0.67863537, 0.37835091, 0.51375407, 0.05768412,
       0.75454649, 0.16285043, 0.66865138, 0.4361611 , 0.15183522,
       0.62695879, 0.54841025, 0.25379113, 0.99654647, 0.75194526,
       0.43407281, 0.27978557, 0.24755256])

In [15]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a+b#this is addition

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.concatenate([a,b])#concatination vertically

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.concatenate([a,b],axis=1)#concatinated horizantally

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [28]:
np.vsplit(a,[2])#splitting in vertical axis


[array([[1., 1., 1.],
        [1., 1., 1.]]), array([[1., 1., 1.]])]

In [42]:
a.reshape(-1,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
ab=np.array((1,2,3,4,5,6,7,8,9))
ab.max()
ab.min()



In [52]:
z=np.array((1,2,3,12,13,14))
z


array([ 1,  2,  3, 12, 13, 14])

In [58]:
q=z+23
q

array([24, 25, 26, 35, 36, 37])