In [1]:
##############-------------numpy axis-------------###############
#1d array=(axis 0)
#2d array=(axis 0,axis 1)
import numpy as np
x=[[1,2,3],[4,5,6],[7,8,9]]

In [2]:
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.sum(axis=0)#(axis 0=rows...summation of rows.)

array([12, 15, 18])

In [4]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [5]:
arr.T#transpose matrix


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
for i in arr.flat:
    print(i)

1  
2  
3  
4  
5  
6  
7  
8  
9  


In [9]:
arr.ndim#dimension of array

2

In [10]:
arr.size

9

In [11]:
arr.nbytes#total bytes consumed

72

In [13]:
arr.argmax()#index of maximum element
arr.argmin()

0

In [14]:
arr.argsort()#indices array for sorting

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [15]:
arr.argmax()#index of max element #9 here

8

In [18]:
arr#for ref

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.argmax(axis=0)#max elements index in each row as ssame for min also.

array([2, 2, 2])

In [16]:
arr.argmin()#index of min element

0

In [20]:
arr1 = np.array([[11,12,13],[14,15,16],[17,18,19]])
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
arr+arr1#addition

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
arr*arr1

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [24]:
np.sqrt(100)#squareroot

10.0

In [25]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.where(arr>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [28]:
np.count_nonzero(arr)#count total non zero elements

9